public enum AttackEnum {
    EQUIP_WEAPON_RANGED,
    EQUIP_WEAPON_MELEE,
    WEAPON_NOT_EQUIP,
    WEAPON_EQUIP,
    WEAPON_NOT_FOUND,
    ATTACK_NO_AMO,
    ATTACK_NO_WEAPON,
    ATTACK_SUCCESS,
    ATTACK_FAILURE,
    PLAYER_DEAD,
    ENEMY_DEAD,
    PLAYER_SUCCESS


    }
